import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

/// One research-grounded follow-up question drafted by the daily LLM step
/// (tools/generate_question_bank.py) from collected paper abstracts.
class BankQuestion {
  const BankQuestion({
    required this.questionKo,
    required this.questionEn,
    required this.rationaleKo,
    required this.sourceIds,
  });

  final String questionKo;
  final String questionEn;
  final String rationaleKo;
  final List<String> sourceIds;

  factory BankQuestion.fromJson(Map<String, dynamic> json) {
    return BankQuestion(
      questionKo: (json['question_ko'] ?? '').toString(),
      questionEn: (json['question_en'] ?? '').toString(),
      rationaleKo: (json['rationale_ko'] ?? '').toString(),
      sourceIds: [
        for (final id in (json['source_ids'] as List? ?? const []))
          id.toString(),
      ],
    );
  }
}

class BankSource {
  const BankSource({required this.id, required this.title, required this.year});

  final String id;
  final String title;
  final String year;
}

/// Question-bank entry for one TCM pattern direction (keyed by the same
/// pattern id as PatternFinderService.patterns).
class PatternQuestionBank {
  const PatternQuestionBank({required this.questions, required this.sources});

  final List<BankQuestion> questions;
  final List<BankSource> sources;
}

/// Loads the bundled research-grounded question bank
/// (`research/question_bank.json`, regenerated by the scheduled GitHub Action
/// whenever new papers arrive). Empty until the first LLM run — callers must
/// degrade gracefully.
class QuestionBankService {
  QuestionBankService._();

  static final QuestionBankService instance = QuestionBankService._();

  static const _assetPath = 'research/question_bank.json';

  Map<String, PatternQuestionBank>? _cache;

  Future<Map<String, PatternQuestionBank>> load() async {
    final cached = _cache;
    if (cached != null) return cached;
    try {
      final raw = await rootBundle.loadString(_assetPath);
      final decoded = jsonDecode(raw);
      final patterns = (decoded is Map<String, dynamic>)
          ? decoded['patterns']
          : null;
      final result = <String, PatternQuestionBank>{};
      if (patterns is Map<String, dynamic>) {
        patterns.forEach((patternId, entry) {
          if (entry is! Map<String, dynamic>) return;
          final questions = [
            for (final q in (entry['questions'] as List? ?? const []))
              if (q is Map<String, dynamic>) BankQuestion.fromJson(q),
          ];
          final sources = [
            for (final s in (entry['sources'] as List? ?? const []))
              if (s is Map<String, dynamic>)
                BankSource(
                  id: (s['id'] ?? '').toString(),
                  title: (s['title'] ?? '').toString(),
                  year: (s['year'] ?? '').toString(),
                ),
          ];
          if (questions.isNotEmpty) {
            result[patternId] = PatternQuestionBank(
              questions: questions,
              sources: sources,
            );
          }
        });
      }
      _cache = result;
      return result;
    } catch (_) {
      _cache = const {};
      return _cache!;
    }
  }

  /// Bank entry for one pattern id, or null when not generated yet.
  Future<PatternQuestionBank?> forPattern(String patternId) async {
    return (await load())[patternId];
  }
}
